# Generated by Django 5.1.2 on 2024-10-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_award',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
            ],
            options={
                'db_table': 'main_judge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'main_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'main_participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'main_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'main_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'main_season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('year_formed', models.IntegerField()),
            ],
            options={
                'db_table': 'main_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
            ],
            options={
                'db_table': 'main_teamhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teamstatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField()),
                ('total_wins', models.IntegerField()),
                ('total_losses', models.IntegerField()),
            ],
            options={
                'db_table': 'main_teamstatistic',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.RemoveField(
            model_name='result',
            name='game',
        ),
        migrations.RemoveField(
            model_name='match',
            name='game',
        ),
        migrations.RemoveField(
            model_name='score',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner_team',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team',
        ),
        migrations.RemoveField(
            model_name='result',
            name='team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='team',
        ),
        migrations.RemoveField(
            model_name='season',
            name='champion_team',
        ),
        migrations.RemoveField(
            model_name='teamstatistic',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamhistory',
            name='team',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='TeamStatistic',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamHistory',
        ),
    ]
