# Generated by Django 5.1.2 on 2024-10-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='award_name',
            field=models.CharField(max_length=100, verbose_name='Название награды'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.seasons', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_date',
            field=models.DateField(verbose_name='Дата игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='judges',
            name='experience_years',
            field=models.IntegerField(verbose_name='Годы опыта'),
        ),
        migrations.AlterField(
            model_name='judges',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя судьи'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='main.teams', verbose_name='Команда 1'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='main.teams', verbose_name='Команда 2'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_team', to='main.teams', verbose_name='Победившая команда'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя участника'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='results',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.IntegerField(verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='results',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.games', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.judges', verbose_name='Судья'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='champion_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teams', verbose_name='Чемпион'),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='event_date',
            field=models.DateField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='event_description',
            field=models.TextField(verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_name',
            field=models.CharField(max_length=100, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='year_formed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год основания'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='total_games',
            field=models.IntegerField(default=0, verbose_name='Всего игр'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='total_losses',
            field=models.IntegerField(default=0, verbose_name='Всего поражений'),
        ),
        migrations.AlterField(
            model_name='teamstatistics',
            name='total_wins',
            field=models.IntegerField(default=0, verbose_name='Всего побед'),
        ),
    ]
